[workspace]
members = [
    "xtask",
    "common/stdio",
    "common/mem",
    "common/executor",
    "libs/thread",
    "libs/time",
    "libs/net",
    "libs/var_bitmap",
    "platforms/guest",
    "platforms/qemu-virt",
    "platforms/qemu-virt-ld",
    "platforms/qemu-sifive_u",
    "platforms/qemu-sifive_u-ld",
    "apps/helloworld",
    "apps/echo",
    "apps/server",
    "apps/client",
    "obj",
]
default-members = ["xtask"]
