[alias]
xtask = "run --package xtask --release --"
make = "xtask make"
asm = "xtask asm"
qemu = "xtask qemu"
guest = "xtask guest"
warn = "fix --allow-dirty --allow-staged --target riscv64gc-unknown-none-elf"
warn-std = "fix --allow-dirty --allow-staged"
