[package]
name = "obj"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { path = "../apps/client", package = "client" }
platform = { path = "../platforms/guest", package = "guest" }
stdio = { path = "../common/stdio" }
executor = { path = "../common/executor" }
thread = { path = "../libs/thread" }
net = { path = "../libs/net" }
mem = { path = "../common/mem", features = ["std"] }

[build-dependencies]
linker = { path = "../platforms/guest-ld", package = "guest-ld" }

[features]
default = ["std"]
std = []

