[package]
name = "obj"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { path = "../apps/helloworld", package = "helloworld" }
platform = { path = "../platforms/qemu-virt", package = "qemu-virt" }
stdio = { path = "../common/stdio" }
net = { path = "../libs/net" }
mem = { path = "../common/mem", features = [] }

[build-dependencies]
linker = { path = "../platforms/qemu-virt-ld", package = "qemu-virt-ld" }

[features]
default = []
std = []

