[package]
name = "guest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
platform = { path = "../platform" }
timer = "0.2.0"
chrono = { version = "0.4.22"}
lazy_static = "1.4.0"
async-std = "1.12.0"
rawsock = "0.3"
pnet = {version  = "0.31.0", features = ["std"]}
spin = "0.9.4"
smoltcp = { version = "0.8.1", default-features = false, features = [
    "phy-raw_socket",
    "alloc",
    "socket-tcp",
    "medium-ethernet",
    "proto-ipv4",
    "log", "verbose"] }
bimap = "0.6.2"
