[package]
name = "qemu-virt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi-rt = {version="0.0.2" , features = ["legacy"]}
uart_16550 = "0.2.18"
spin = "0.9.4"
riscv = "0.9.0"
good_memory_allocator = "0.1.7"

platform = { path = "../platform" }
qemu-virt-ld = { path = "../qemu-virt-ld"}

kernel-context = {path = "./kernel-context", features = []}
mem = {path = "../../common/mem"}
executor = {path = "../../common/executor"}
collections = {path = "../../common/collections"}

virtio-drivers = "0.1.0"
dtb-walker = "0.1.3"
stdio = {path = "../../common/stdio"}

isomorphic_drivers = { git = "https://github.com/rcore-os/isomorphic_drivers", rev = "f7cd97a", features = ["log"] }
volatile = "0.3"

# async_executor 
async-task = { version = "1.3.0", default-features = false}
futures = { version = "0.3.25", default-features = false, features = ["async-await"]}
