[package]
name = "qemu-virt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi-rt = {version="0.0.2" , features = ["legacy"]}
uart_16550 = "0.2.18"
spin = "0.9.4"
riscv = "0.9.0"

platform = { path = "../platform" }
qemu-virt-ld = { path = "../qemu-virt-ld"}

kernel-context = {path = "./kernel-context", features = []}
mem = {path = "../../common/mem"}

virtio-drivers = "0.1.0"
device_tree = { git = "https://github.com/rcore-os/device_tree-rs", rev = "2fa8411" }

stdio = {path = "../../common/stdio"}
